### ISSUE TITLE
Issue with enabling addon

### ISSUE THREAD

**Issue by klaus-woelkchen** [mrachinskiy/commotion#11]
Error message:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\lenny\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\commotion-master\__init__.py", line 122, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'CommotionShapeKeyCollection'

is there something i can do on my side?

**Comment by mrachinskiy** [comment]
Download add-on using link from the [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).
