### ISSUE TITLE
Error installing addon

### ISSUE THREAD

**Issue by Sand0858** [mrachinskiy/commotion#34]
Installing zip files, I get the following error. How can I fix it?

[Blendr version] 4.0.2
[error]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\LSH\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\commotion-master\__init__.py", line 25, in <module>
    _essential.check(var.ADDON_DIR / "mod_update", bl_info["blender"])
  File "C:\Users\LSH\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\commotion-master\_essential.py", line 37, in check
    raise error
FileNotFoundError: 

!!! READ INSTALLATION GUIDE !!! READ INSTALLATION GUIDE !!! READ INSTALLATION GUIDE !!!

**Comment by mrachinskiy** [comment]
If error occurs on add-on activation, it means you are trying to install add-on repository instead of release. Make sure you download add-on release using link provided in [step one of installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by Sand0858** [comment]
Ah! Thank you so much ;)
