### ISSUE TITLE
Addon Updating issue on Blender 2.82.6 , macos 10.13.6 & Commotion v2.1.1

### ISSUE THREAD

**Issue by Oxervision** [mrachinskiy/commotion#4]
Hi,
I found a error message in console when Blender starts with addon activated. This is the message:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/User/Library/Application Support/Blender/2.82/scripts/addons/commotion/mod_update/lib.py", line 96, in _update_check
    with urllib.request.urlopen(var.UPDATE_RELEASES_URL, context=ssl_context) as response:
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/Blender/BLENDER 2.82/Blender.app/Contents/Resources/2.82/python/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
And in the addon preferences it appears "**Checking...**" and this message doesn't change.

![Update issue](https://user-images.githubusercontent.com/46649474/72665293-1f263080-3a07-11ea-8a54-018c8d8632f0.jpg)

**Comment by mrachinskiy** [comment]
Thanks for the report, fixed in v2.1.2
